### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jameskraus** [derrickpelletier/react-loading-overlay#11]
A demo and working screenshot of this project would help people understand it at a glance. I would recommend a jsbin/webpackbin since that's easiest to set up.

FWIW, I used webpackbin to try it out. Here's my super basic webpackbin:
https://www.webpackbin.com/bins/-KrXKsbxORpKQSS5AVtl

**Comment by derrickpelletier** [comment]
There _was_ a gif in the readme... looks like it's a dead link now though. 👎 

I'll put a new gif in the readme and maybe link to your bin, thanks!

**Comment by moribellamy** [comment]
if it helps: https://imgur.com/42ElaHG

**Comment by derrickpelletier** [comment]
Added a little screenshot :)
