### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by vikramtrs** [derrickpelletier/react-loading-overlay#15]
Hello, this loader is not working in IE.. I just see an overlay and the spinner looks like a dot..

**Comment by derrickpelletier** [comment]
Provide more details, please. Browser version, OS version for starters.

**Comment by vikramtrs** [comment]
@derrickpelletier it's IE 11 on Windows 7..

**Comment by derrickpelletier** [comment]
interesting! Thanks for the details.

Please feel free to submit a PR, otherwise going to be a while until I get to it i think

**Comment by nponiros** [comment]
I guess you would have to detect IE by user-agent sniffing to set the bigger stroke-dasharray value. I don't think this should be in the library. Maybe just mention the workaround in the readme (I could probably find the time during the weekend to write something in the readme). Since I already have to detect IE in my app I just put the workaround into my IE stylesheet.

**Comment by vikramtrs** [comment]
Hi @nponiros can you pls share the css modifications for IE?

**Comment by derrickpelletier** [comment]
I'm not opposed to using a 3rd party spinner here instead of the one i dropped in (like https://github.com/tsuyoshiwada/react-md-spinner or something similar?)

I'd also love to have a prop in place for people to provide their own spinner component into the lib.

**Comment by nponiros** [comment]
@vikramtrs `body.isIE svg circle { stroke-dasharray: 100,200 }` and use feature testing/user agent sniffing to set `isIE` class to body. You can have a look at https://stackoverflow.com/questions/17907445/how-to-detect-ie11 for some ideas.

@derrickpelletier keeping the current spinner and allowing a custom spinner sounds like a good idea. What I needed to do is show a spinner with text (like your lib does) and change the text every few seconds. Maybe this is also an interesting feature for this lib.

**Comment by derrickpelletier** [comment]
custom spinners are supported now
