### ISSUE TITLE
Breaking change on 0.2.8

### ISSUE THREAD

**Issue by hectorsabina** [derrickpelletier/react-loading-overlay#16]
Hi, after bumping this dependency from `0.2.5` to `0.2.8` I'm starting to see an error related with `LoadingOverlayWrapper`.

> invariant.js?7313:42 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `LoadingOverlayWrapper`.

Going back to 0.2.5 fixed the issue for me.

**Comment by derrickpelletier** [comment]
Realize this has been a while, sorry. I've tried to recreate what you're experiencing but I can't. if this is still an issue please post some more details, maybe an example of how you're using it!
