### ISSUE TITLE
Custom style on LoadingOverlay

### ISSUE THREAD

**Issue by AllenFang** [derrickpelletier/react-loading-overlay#17]
HI @derrickpelletier firslty, thanks this awesome repo, I'm going to use it in my site prodject, however, I found seems like we can not custom the styles on LoadingOverlay component: https://github.com/derrickpelletier/react-loading-overlay/blob/master/src/LoadingOverlay.js#L93

If yes, I think it will be useful to have this customization feature and I can open a PR for it
How do you said?

Regards,
Allen

**Comment by derrickpelletier** [comment]
Would love for it to be more customizable!

**Comment by AllenFang** [comment]
@derrickpelletier coool, I'll make a PR for this, if the props name is`overlayStyle` is that ok for you? 

Thanks your quick response 👍
