### ISSUE TITLE
Custom text with font-awesome's icon spinner 

### ISSUE THREAD

**Issue by harrysoer** [derrickpelletier/react-loading-overlay#19]
Hi, I may have found a way to have my own custom spinner icon by over-riding the text props but I'm receiving an error but it works perfectly. Take a look at my screenshots

Code:
![code loading](https://user-images.githubusercontent.com/18716069/36081376-087436c0-0fd9-11e8-8c51-8af4a57b0c8d.png)

Output:
![output](https://user-images.githubusercontent.com/18716069/36081379-14748196-0fd9-11e8-831c-0834c6b41d2f.png)

Error message:
![errmsg](https://user-images.githubusercontent.com/18716069/36081394-30c23a64-0fd9-11e8-8ad3-11ca127b23ff.png)

**Comment by derrickpelletier** [comment]
Yeah, the text prop only accepts a string! Definitely on my radar to add a custom spinner though, so i'll leave this issue open

**Comment by derrickpelletier** [comment]
supported now
