### ISSUE TITLE
Logs of the loader for each render.

### ISSUE THREAD

**Issue by fBruzja** [derrickpelletier/react-loading-overlay#22]
The package logs to the console after each render the object of the loader. Is there any way i can remove this behaviour, since i do not want them to show to the client.

**Comment by derrickpelletier** [comment]
Hm, odd. I wonder what is doing the log. There are no logs from the source itself!

**Comment by minuss273** [comment]
There are no logs on the project i am working on either, since i am using eslint and it obviously won't let me build the project if i have any 'console.log'-s in the code.
