### ISSUE TITLE
incompatible with webpack 3?

### ISSUE THREAD

**Issue by CraigMeng** [derrickpelletier/react-loading-overlay#24]
Hi guys,

I used this library in my project created by create-react-app, which use webpack 3.8.1. But I keep getting this errors:>

invariant.js:42 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `LoadingOverlayWrapper`.

Any ideas on this?

**Comment by derrickpelletier** [comment]
It's possible! I've updated everything. Not sure if you're still using this, but v1.0.0 probably fixed this.
