### ISSUE TITLE
Loader not working ..

### ISSUE THREAD

**Issue by anjariamohnish** [derrickpelletier/react-loading-overlay#28]
Loader works for the first time next time it renders but doesnt get any style so the screen becomes white,  is it because of Material UI which I am using in my project

      <Loadable
        active={this.props.showLoader}
        spinner
        text={this.props.loaderText}>
        <Switch>
          <Route exact path="/" component={Login} />
          <Route exact path="/login" component={Login} />
          <Route exact path="/register" component={Registration} />
          <Route exact path="/dashboard" component={Dashboard} />
          {/* <Route component={404Component} /> */}
        </Switch>
        <NotificationContainer />
      </Loadable>

**Comment by derrickpelletier** [comment]
@anjariamohnish sorry for not replying sooner. The interface and styles were quite old, I've updated them. Please try installing `v1.0.0` and if you experience the same problem i'll help you debug if i can.
