### ISSUE TITLE
Loding not showing (showing in white Background)

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [derrickpelletier/react-loading-overlay#34]
I have a code : 

`<LoadingOverlay
                    active={this.state.isLoading}
                    spinner
                    text={this.state.loadingMsg} >
                     <div className="div-area-child-list">
                            {mainContent}
                        </div>
</LoadingOverlay>`

and class for "div-area-child-list" : 

`.div-area-child-list {
      position: fixed;
      top: 8%;
      bottom: 14%;
      left: 0%;
      right: 0%;  
      overflow-y: scroll;
    }`

Then the Loading is not shown at all... 

How to solve this?

**Comment by derrickpelletier** [comment]
Very hard to debug without an example. If you can put a page up somewhere it could help. But this just sounds like a styling issue to me, check out https://github.com/derrickpelletier/react-loading-overlay#custom-styling-nail_care for details on how to customize the styles for your case.
