### ISSUE TITLE
rounded border

### ISSUE THREAD

**Issue by slavagu** [derrickpelletier/react-loading-overlay#38]
I've tried to set `border-radius: 4px` using wrapper and content styles override but it didn't work. Is there a way to specify rounded corners for the overlay?

**Comment by derrickpelletier** [comment]
Can you share your code for this issue?

**Comment by slavagu** [comment]
Started doing codepen demo and found the new version 1.0.1 does support the customization! My bad I didn't upgraded the package. Just for reference that's what I'm doing:
```js      
<LoadingOverlay
  styles={{
    overlay: base => ({
      ...base,
      borderRadius: '4px',
    }),
  }}
  active
  spinner
>
  {children}
</LoadingOverlay>

```
Thanks!

**Comment by derrickpelletier** [comment]
🙏
