### ISSUE TITLE
Add an option to cover the whole page

### ISSUE THREAD

**Issue by ysabih** [derrickpelletier/react-loading-overlay#40]
Is it possible to add a prop to cover the whole page and not just the parent component? Or is there a quick way to have it with custom styling ?

**Comment by PedroCavaleiro** [comment]
Also searching for this feature

**Comment by derrickpelletier** [comment]
It's either a question about how you structure your app in regards to loading, or some custom styling yeah. As for the exact styling it's very hard to suggest anything without knowing your app, but if you read the docs in the readme, there are plenty of options for styling.

Nothing should be stopping you from doing what you're asking with the available options 🙏

**Comment by alzin** [comment]
This works for me by adding it to the App.css file,

div._loading_overlay_wrapper {
    position: unset;
  }
