### ISSUE TITLE
Error when trying to use the overlay 

### ISSUE THREAD

**Issue by mattany** [derrickpelletier/react-loading-overlay#59]
Getting the following warning when using the overlay. The overlay and content work fine but the warning appears still.

"Warning: Failed prop type: LoadingOverlayWrapper: prop type `styles.content` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`."

Steps to reproduce:
Try using an overlay with content (as in the examples given in the docs). This happens both when the content property is a function, or an object

**Comment by perryraskin** [comment]
I am running into the same issue 🥲

**Comment by globalmatt** [comment]
I started getting this warning after upgrading to React 18. The overlay still works OK.

Edit: Looks to be a duplicate of #56

**Comment by mattany** [comment]
> Edit: Looks to be a duplicate of #56

Yes, I believe you are right. Closing this one.
