### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Sigfried** [derrickpelletier/react-loading-overlay#6]
First, styled-components is listed in package.json as a dev dependency but it's apparently a regular dependency. I had to install it after npm installing react-loading-overlay. After fixing that, it's still not working for me. My render code looks like this:

    if (conceptStats && typeof conceptCount !== 'undefined') {
      concepts =  <Concepts  
                    conceptStats={conceptStats} 
                    conceptCount={conceptCount} 
                  />;
    }
    return  <Loadable
              active={isLoading}
              spinner={true}
              text='Loading concept stats...'
              >
                {concepts}
            </Loadable>

I see nothing whether my data is loaded or not.

It would be nice, btw, not to have to test that in the render explicitly -- if Loadable is active, it shouldn't even try to display the children.

Thanks!

**Comment by derrickpelletier** [comment]
Sorry for not getting to this sooner, i missed the notification somehow!
Will definitely address the dependency shortly, thanks for the heads up.

Regarding your second point, I guess you could go two ways. `{concepts}` could just be `{!isLoading && concepts}` which seems pretty trivial to me. Alternatively it would probably mean adding _another_ prop to specify this behaviour, as there are many cases where you might want a loader visible over content (when saving/updating or something similar, you might want to overlay the component in question, for example).

**Comment by MichaelRando** [comment]
still broken?

**Comment by Sigfried** [comment]
That's a reasonable point, @derrickpelletier.

I just noticed your response because of @MichaelRando's comment. So maybe Michael is having the same problem I was, that even when isActive is set to true, I wasn't seeing the overlay.

**Comment by ydornala** [comment]
Issue with styled-components dependency @derrickpelletier

**Comment by derrickpelletier** [comment]
dependency issue patched in commit: 4dc124730c0dec867f9b3b7884086a8b02e39873
`v0.2.4` on npm

Let me know if that doesn't fix it!
