### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by tudorg-telenav** [derrickpelletier/react-loading-overlay#8]
using the latest react versions, I'm receiving a warning message about this deprecation issue:

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

the stack trace points to LoadingOverlay.js

**Comment by arclauss** [comment]
Submitted PR #10 that will fix this and another deprecation issue.

**Comment by arclauss** [comment]
@tudorg-telenav ,  this is fixed in v0.2.5, @derrickpelletier , this is can now be closed.
