### ISSUE TITLE
Deprecation warning with ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by louisgv** [derrickpelletier/react-loading-overlay#9]
> Note: ReactTransitionGroup and ReactCSSTransitionGroup are both deprecated as of React v15.5.0. The recommendation is to use TransitionGroup and CSSTransitionGroup from 'react-transition-group' instead.

Referring to this document:
https://facebook.github.io/react/docs/animation.html

**Comment by kingllama** [comment]
+1 having issues with this myself.

**Comment by derrickpelletier** [comment]
Feel free to submit a PR.
Might be a bit til i get to it

**Comment by AlexChaseJones** [comment]
+1. Application failing with `webpackHotDevClient.js:231 Error in ./~/react-loading-overlay/lib/LoadingOverlay.js
Module not found: 'react/lib/ReactCSSTransitionGroup' in /Users/.../react-loading-overlay/lib

 @ ./~/react-loading-overlay/lib/LoadingOverlay.js 27:31-75`
